In [34]:
import numpy as np
import pandas as pd
from sklearn import datasets

# Charger le jeu de données et retourner une frame Pandas
# data = load_wine(return_X_y=False, as_frame=False)
# dataFrame = load_wine(return_X_y=False, as_frame=True)
# dataFrame2 = load_wine(return_X_y=True, as_frame=True)

# Afficher le jeu de données chargé
# dataFrame2.describe()

wine = datasets.load_wine()
print(wine.data)

# wine.target
print(wine.items)


[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
<built-in method items of Bunch object at 0x000001D508F63790>
